### ISSUE TITLE
Is there a way to reduce the spacing between keys?

### ISSUE THREAD

**Issue by drGarbinsky** [ibnuda/dactyl-keyboard#102]
I am looking to reduce the space between the keys by around .5 mm  either between rows and or columns. I realize that as the ends of the columns converge based on curvature settings this could cause an issue but I'd like to experiment with such an option. Any idea if there is a way to do that?

**Comment by yejianfengblue** [comment]
The source code options

https://github.com/ibnuda/dactyl-keyboard/blob/84e86a58582954f60f7844ef571f62e69b9fd02d/src/dactyl_keyboard/common.clj#L9-L16

Change the source code and run the server locally 
https://github.com/ibnuda/dactyl-keyboard#development

**Comment by drGarbinsky** [comment]
thank you!

**Comment by albert-ying** [comment]
Hi @drGarbinsky, did you manage to do it? The esrille actually provides the small MX keycap that could support a key spacing of 17.5 mm http://www.esrille.com/keyboard/.

I'm wondering if it is possible to create a smaller version of Dactyl

**Comment by yejianfengblue** [comment]
> Hi @drGarbinsky, did you manage to do it? The esrille actually provides the small MX keycap that could support a key spacing of 17.5 mm http://www.esrille.com/keyboard/.
> 
> I'm wondering if it is possible to create a smaller version of Dactyl

Another factor that stops you from making a keyboard with less key spacing is the standard key switch size (cherry mx standard width and height is nearly 16mm) and standard keycap size (nearly 18mm).

Besides the cherry mx standard, there is one kind of key switchs called low profile key switch, but they are a bit expensive and less choice. What is worse is there is no compatibility between difference manufacturer. 

See 
- low profile key switch disaster https://youtu.be/2qzxGP9NStc
- low profile key cap with smaller dimension https://mkultra.click/mbk-choc-keycaps, https://mkultra.click/moergo/
- mass production keyboard with low profile key switch and concave surface  https://moergo.com/
- there are many DIY keyboard with low profile key switch, google yourself

**Comment by albert-ying** [comment]
Thank you so much @yejianfengblue . The moergo looks SUPER interesting to me!

**Comment by drGarbinsky** [comment]
> Hi @drGarbinsky, did you manage to do it? The esrille actually provides the small MX keycap that could support a key spacing of 17.5 mm http://www.esrille.com/keyboard/.
> 
> I'm wondering if it is possible to create a smaller version of Dactyl

Here is an example with 1 and -2 for those values. Goes without saying, a test print is needed to know how the keys will fit. Some keys may need some trimming

![image](https://user-images.githubusercontent.com/10457430/197255766-5cbe048c-4215-4ff1-94c3-14097edee8bb.png)


which I am doing now....

**Comment by drGarbinsky** [comment]
Results 
![Uploading 546E10D5-8740-49BE-898E-08AEAA58915D.jpeg…]()

**Comment by drGarbinsky** [comment]
Results
i think this is doable. With a flatter profile you could get them even closer. The limit is the keys on the upper row. If your willing to trim the switches you could get another mm 
![1E8C7B70-28D5-48A7-A4F8-14CA78BCC629](https://user-images.githubusercontent.com/10457430/197362035-a6fd3841-9cf2-4cf8-91b9-a61b230933b8.jpeg)

**Comment by albert-ying** [comment]
It looks nice! How about the horizontal spacing? It seems that there is still some space between columns.

**Comment by drGarbinsky** [comment]
That model has a reduced spacing but it is limited by the gap along the top row. Using a flatter profile will allow for a tighter column spacing

**Comment by drGarbinsky** [comment]
Here is [the end result](https://www.printables.com/model/314112-dactyl-manuball)
Here is [the forked code](https://github.com/drGarbinsky/dactyl-keyboard)
