### ISSUE TITLE
Strange L shape added when using TRRS jack

### ISSUE THREAD

**Issue by CaffeinatedOpe** [ibnuda/dactyl-keyboard#105]
![image](https://user-images.githubusercontent.com/60710307/150650750-bc571ef5-0979-42a2-b109-51d43b8a6a7c.png)
this shape was added into the model, and i'm not sure why. how do i remove it? it only shows up when the trrs jack is selected.

**Comment by yejianfengblue** [comment]
The L hook is atmega32u4 pro micro holder, see https://github.com/yejianfengblue/dactyl-generator-demo#internal-connector-trrs-micro-usb. 

You can manually delete the openscad code by 
1. select openscad memu `window` -> `editor`
2. right click the L hook, there will be a popup, click the `cube`
3. the editor should jump to the code of the L hook
```
union () {
  difference () {
    translate ([-94.9015632882982, 24.40298907331629, 16.208123960789713]) {
      cube ([6, 12, 12], center=true);
    }
    translate ([-95.9015632882982, 23.40298907331629, 16.208123960789713]) {
      cube ([4, 10, 12], center=true);
    }
  }
  translate ([-60.02565784429761, 37.394528789935315, 2]) {
    cube ([19, 12, 4], center=true);
  }
  union () {
    translate ([-73.6256578442976, 37.394528789935315, 2]) {
      cube ([10.2, 12, 4], center=true);
    }
  }
}
```
4. delete difference() and everything inside it
```
  difference () {
    translate ([-94.9015632882982, 24.40298907331629, 16.208123960789713]) {
      cube ([6, 12, 12], center=true);
    }
    translate ([-95.9015632882982, 23.40298907331629, 16.208123960789713]) {
      cube ([4, 10, 12], center=true);
    }
  }
``` 
5. press F5 to refresh. The L hook should be deleted

**Comment by CaffeinatedOpe** [comment]
Okay, thank you very much!
