### ISSUE TITLE
Dactyl thumb cluster with 8 keys

### ISSUE THREAD

**Issue by jgandert** [ibnuda/dactyl-keyboard#13]
First of all: Wow, this is one of the most amazing things I've seen in the MK community. Thanks for creating this!

My request is about the thumb cluster. I personally think the thumb cluster is really useful in Dactyl-style keyboards, but my experience with the 2u keys is that they're great, but would basically provide twice the benefit by splitting them up. I usually only hit the top half of the 2u key, so having another key below would be really useful for me. It would also allow for a better thumb curvature to make all the thumb keys easier to reach (similar to what is true for the main keys' curvature).

![Marked Dactyl for clarification](https://user-images.githubusercontent.com/3063858/83954934-e370f380-a84d-11ea-8402-338756c077c9.png)

(*Image source:* https://github.com/adereth/dactyl-keyboard/blob/master/README.md)

**Comment by ibnuda** [comment]
OK. I will try to do that. should be doable.

**Comment by ibnuda** [comment]
@CreamyCookie, please check the site again. it should be able to generate 8 thumb keys, now. and if you're ok with it, please close the issue.

thanks.

**Comment by jgandert** [comment]
@ibnuda Thanks so much! I haven't (yet) build a single keeb (using Kinesis Advantage atm) so I can't fully evaluate it. That said, the thumb cluster is curved and it looks good to my untrained eye :)

Really cool, thank you!

**Comment by jgandert** [comment]
Pictures from OpenSCAD

![1](https://user-images.githubusercontent.com/3063858/83980129-95262800-a913-11ea-9c6f-8292bfafa3a6.png)
![2](https://user-images.githubusercontent.com/3063858/83980131-96575500-a913-11ea-8ec9-a545415f6f7c.png)
![3](https://user-images.githubusercontent.com/3063858/83980132-96575500-a913-11ea-91f1-9dbe26f1f6e9.png)
