### ISSUE TITLE
Manuform with Lightcycle thumb cluster

### ISSUE THREAD

**Issue by jgandert** [ibnuda/dactyl-keyboard#15]
**Edit**: Of course, a Lightcycle with thumbcluster angled like Manuform would be just as cool

While I'm personally not a fan of Manuform's spaced out thumb key positions (too far away imo), I really like the thumb cluster angle. It makes a lot of sense since, of course, our thumbs are opposable.

So I think something like the following could be interesting (especially with #14):

![manuform DMOTE 4 mockup](https://user-images.githubusercontent.com/3063858/84542895-a5b31580-acfa-11ea-8726-5e3c1c8ed38b.png)

Older mockup:

![manuform cycle: old mockup](https://user-images.githubusercontent.com/3063858/84435147-99af5100-ac31-11ea-8c4d-e35b61503070.jpg)

*(Image source: http://blog.pzs.me/posts/dactyl-manuform-log/index.html)*

**Comment by ibnuda** [comment]
something like this? if it's ok, please close it.
![Schermafdruk_2020-06-15_02-23-05](https://user-images.githubusercontent.com/8169908/84602106-3a5e7480-aeaf-11ea-93b3-c431aafefc55.png)

**Comment by jgandert** [comment]
@ibnuda Thanks so much for these quick fixes / changes!

Could it be that the web generator is not yet updated? I can select a negative angle but the resulting file has none and the overlap from #18 is still there.

This is with -20 thumb angle:

 ![overlap](https://user-images.githubusercontent.com/3063858/84699314-98dc2f00-af51-11ea-9117-b6e6cca35bcb.png)

[Settings as always (just in case)](https://user-images.githubusercontent.com/3063858/84699490-e35dab80-af51-11ea-8f90-c27067a17396.png)

**Comment by ibnuda** [comment]
ah, you're right. I didn't touch the handler function. I will fix it in a few hours.

**Comment by jgandert** [comment]
Okay, I'll try again later! =)

**Comment by ibnuda** [comment]
these following images use your setting.

![Schermafdruk_2020-06-16_14-39-20](https://user-images.githubusercontent.com/8169908/84746001-8dcfe000-afdf-11ea-9a65-2d274cb0d23b.png)

![Schermafdruk_2020-06-16_14-39-35](https://user-images.githubusercontent.com/8169908/84746071-a5a76400-afdf-11ea-8457-1ea917dce19c.png)

while the following images use pi/-9 for thumb tenting angle. i also have put it live.

![Schermafdruk_2020-06-16_14-41-15](https://user-images.githubusercontent.com/8169908/84746146-beb01500-afdf-11ea-83da-2200ddb4d050.png)
![Schermafdruk_2020-06-16_14-41-43](https://user-images.githubusercontent.com/8169908/84746150-c1ab0580-afdf-11ea-88ae-61dd4b9d761c.png)

**Comment by jgandert** [comment]
First of all, thank you. There are a couple issues (I'll number them for easy reference), but I like this. =)

1. The artifact is still there (but maybe it's not a problem?): 

![lightcycle - col12 row30 tent7 thumb_tent-8 (BUG)2](https://user-images.githubusercontent.com/3063858/84826593-7581b480-b023-11ea-98d3-478cbe539cfa.png)


---

2. Do you think the two keycaps between thumb cluster and main area could intersect? (There's no keycaps option in the Lightcycle settings to test this.)  

![lightcycle - col12 row30 tent7 thumb_tent-8 (top thumb - could keycaps intersect)](https://user-images.githubusercontent.com/3063858/84820559-23886100-b01a-11ea-9bfb-76a89c156e78.png)

 At first, it seems that moving the thumb cluster away would solve that, but I think that would be problematic, since the thumb cluster is already a bit too far away.



---

3. Could this small protrusion in green be removed or covered up?

![lightcycle - col12 row30 tent7 thumb_tent-8 (top thumb - protrusion - difference red hmm)](https://user-images.githubusercontent.com/3063858/84826391-2dfb2880-b023-11ea-99e4-030387ff6148.png)




----

I think an increased thumb curvature would make this really really good. To clarify #14 I've added a small photoshop edit.

**Comment by ibnuda** [comment]
thumb column curvature: pi/9
thumb row curvature: pi/9
thumb-tenting-angle: pi/9
![Schermafdruk_2020-06-17_17-10-16](https://user-images.githubusercontent.com/8169908/84885810-bf1edd80-b0bd-11ea-8189-b8c1ff143bf6.png)

thumb column curvature: pi/9
thumb row curvature: pi/9
thumb-tenting-angle: pi/-9
![Schermafdruk_2020-06-17_17-11-59](https://user-images.githubusercontent.com/8169908/84885924-e4abe700-b0bd-11ea-8526-11214face2cc.png)

and the artifact in pic 1 & 3 are not there anymore.

**Comment by jgandert** [comment]
Fantastic job. Thanks a ton! =D

My current favorite ([settings](https://user-images.githubusercontent.com/3063858/84950515-59e3e000-b0ef-11ea-90ef-75410dbdfcd2.png)): 
![current best 3](https://user-images.githubusercontent.com/3063858/84950463-3de03e80-b0ef-11ea-8541-203da1aca40d.png)
