### ISSUE TITLE
Ring finger key intersects with border

### ISSUE THREAD

**Issue by jgandert** [ibnuda/dactyl-keyboard#19]
The area where the keycap would be, seems to intersect with the border / rim:

![intersects](https://user-images.githubusercontent.com/3063858/84951347-96fca200-b0f0-11ea-90b5-dd30f8836842.png)

Zoomed out: 
![intersects 2](https://user-images.githubusercontent.com/3063858/84951563-e5aa3c00-b0f0-11ea-8987-2ced1a0d882a.png)

[settings](https://user-images.githubusercontent.com/3063858/84950515-59e3e000-b0ef-11ea-90ef-75410dbdfcd2.png)

If it's not too hard to do, I'd love an option to disable the whole border.  Not that I dislike the border, but a floating key design like the Dactyl Manuform does look interesting too.

**Comment by ibnuda** [comment]
no-border:
![short-wall](https://user-images.githubusercontent.com/8169908/85024435-447abe80-b1a0-11ea-929a-48df9b402f11.png)

with-border:
![tall-wall](https://user-images.githubusercontent.com/8169908/85024518-61af8d00-b1a0-11ea-901e-d403911b59fa.png)

are you sure you want to use that kind of setting? if so, please check the site.

**Comment by jgandert** [comment]
"to border or not to border" love it  :smile: 

I've created a new issue for the borderless idea and added some feedback: #20

Thanks for the the option and the fix!
