### ISSUE TITLE
How do you view the left hand side of the case?

### ISSUE THREAD

**Issue by blakedietz** [ibnuda/dactyl-keyboard#2]
Checking out the refaktor branch and puling latest. After installing everything and generating the file I only see the right hand side of the case that's generated by the sweet web gui you created. How do I view the left hand of the board? I'm a newbie to open scad, so I'm wondering if I'm missing anything.

Also, let me know if you need any help with the project. The dactyl manuform is my favorite board and I'm currently in the process of building a second and stopped by to this repo because you've got the hot swap support.

**Comment by Razerban** [comment]
There are two options:
1- You generate the STL out of the myfile.scad generated and use any tool for 3D modeling (Fuse 360 or Tinkercad for instance) and mirror the object. (Cleanest solution)
2- Or you could Add this code to the end of manuform.clj file to generate the left half and the plate to things directory
```clojure
(spit "things/left-plate.scad"
         (write-scad (mirror [-1 0 0] (right-plate c))))

(spit "things/left.scad"
         (write-scad (mirror [-1 0 0] (model-right c))))
```

**Comment by ibnuda** [comment]
what has @razerbann said is correct. and to make it less cumbersome for user, I will add an option to pick either side.

**Comment by ibnuda** [comment]
fixed and deployed.

**Comment by blakedietz** [comment]
Hey, thank you for the updates. Seriously.
