### ISSUE TITLE
Lightcycle: Option for wall thickness

### ISSUE THREAD

**Issue by jgandert** [ibnuda/dactyl-keyboard#26]
If not too time consuming, I think it would be cool to have a thickness option for the wall, to give the lightcycle an even sturdier feel.

**Comparision at the same zoom level**
![lightcycle v manuform wall thickness 1](https://user-images.githubusercontent.com/3063858/85230940-ac751300-b3f3-11ea-93a7-4de8ca62c372.png)

![lightcycle v manuform wall thickness 2](https://user-images.githubusercontent.com/3063858/85230941-af700380-b3f3-11ea-887e-e974ca99ddd5.png)

**Comment by ibnuda** [comment]
i made an option to use `thick-wall` which 3 mm thick. please check the site.

**Comment by CreamyCookie** [comment]
@ibnuda Thank you! I think 3 mm might be a bit too much. Maybe 2? (light green)





![thick](https://user-images.githubusercontent.com/3063858/85333367-c12bd680-b4d9-11ea-9fad-e7a0134f00ed.png)

**Comment by jgandert** [comment]
@ibnuda I think 3 mm might be a bit too much. I've marked 2mm in light green, which seems okay:





![thick](https://user-images.githubusercontent.com/3063858/85333367-c12bd680-b4d9-11ea-9fad-e7a0134f00ed.png)

I'm closing this though, since the main feature was implemented. Thanks!
