### ISSUE TITLE
Manuform and Lightcycle: Option to remove lower outer pinky key

### ISSUE THREAD

**Issue by jgandert** [ibnuda/dactyl-keyboard#29]
I think the pinky is doing too much work in general, and the lower left- or rightmost pinky key seems very hard to reach, so it would be useful to have an option to remove it while keeping the other keys in that row. 

The makers of the Kinesis Advantage also chose to not have a key there:

![kb600-oh-fullsize](https://user-images.githubusercontent.com/3063858/85453244-f8fb5280-b59b-11ea-959e-4bbb5ef53737.png)

It also makes the shape symmetrical (or nearly in Manuform's case), since both Manuform and Lightcycle don't have the key in the bottom inner position to allow for better thumb placement. But I guess being more symmetrical is not necessarily a benefit.

**Comment by ibnuda** [comment]
something like these? both keyboards only hide the lowest pinky key when they use bottommost row and column more than 5.

lightcycle:
![Schermafdruk_2020-06-29_13-03-00](https://user-images.githubusercontent.com/8169908/85978460-fd46c600-ba08-11ea-8eb9-c53f95ea57c9.png)

manuform:
![Schermafdruk_2020-06-29_13-03-32](https://user-images.githubusercontent.com/8169908/85978468-ffa92000-ba08-11ea-88fe-0d73805a410e.png)

if so, please check the site. it lives already.

**Comment by jgandert** [comment]
Thanks!
