### ISSUE TITLE
Manuform export doesn't work for all fields

### ISSUE THREAD

**Issue by jgandert** [ibnuda/dactyl-keyboard#30]
After changing every field, so the config looks like this:

![e](https://user-images.githubusercontent.com/3063858/85930975-e4cb9400-b8c0-11ea-812a-6af54e595821.png)

This was exported

`{"keys":{"columns":4,"rows":3,"thumb-count":"four","last-row":"zero","switch-type":"alps","inner-column":true},"curve":{"alpha":14,"beta":30,"centercol":1,"tenting":11},"connector":{"external":false,"trrs":false,"micro-usb":false},"form":{"hotswap":true,"stagger":true,"wide-pinky":true,"height-offset":10,"wire-post":true,"screw-inserts":true},"misc":{"keycaps":true,"wrist-rest":false,"integrated-wrist-rest":true,"right-side":false,"case":true}}`

None of the "connector" entries ("micro-usb" etc.) match and the "stagger" should be false.

**Comment by ibnuda** [comment]
it should've been fixed and live at the site. sorry for these bugs. i always open the project past midnight.

**Comment by jgandert** [comment]
Thanks! No problem. Finding time for these projects can be hard sometimes.
