### ISSUE TITLE
Manuform: Configurable middle finger height offset

### ISSUE THREAD

**Issue by jgandert** [ibnuda/dactyl-keyboard#33]
Something that I've only noticed just now is that the height offset of the middle finger is actually a bit too extreme (at least for me), so it would be cool if it was configurable. 

![manuform2c](https://user-images.githubusercontent.com/3063858/86050013-7539de00-ba53-11ea-9033-cb40026d0b28.png)

![manuform2a](https://user-images.githubusercontent.com/3063858/86051064-1d03db80-ba55-11ea-937a-271893a30273.png)

When I let my fingers hover over the keyboard the difference between ring and middle finger is actually pretty minor.

While not perfect, here's the Advantage again for reference:

![kinesis advantage (1)](https://user-images.githubusercontent.com/3063858/86050435-2476b500-ba54-11ea-9004-ca8707bfa07b.png)
![kinesis advantage (2)](https://user-images.githubusercontent.com/3063858/86050440-26d90f00-ba54-11ea-912a-86703072dd1c.png)

**Comment by ibnuda** [comment]
should be fixed already. please check the site.

**Comment by jgandert** [comment]
@ibnuda Awesome. Thank you once again! =D
