### ISSUE TITLE
Manuform: fine tune (parametric) column stagger offsets

### ISSUE THREAD

**Issue by dereknheiley** [ibnuda/dactyl-keyboard#34]
![d-hands](https://user-images.githubusercontent.com/3382160/86537417-f57d9a80-bebc-11ea-9f73-0f09d952d1bf.jpg)

It would be nice to be able to fine tune the column stagger, i think the redox manuform has better (for my hand) pinky, and index finger column staggers, so it would be great to have the option to see the default column staggers, and be able to tweak them.

**Comment by ibnuda** [comment]
should be fidex already

**Comment by dereknheiley** [comment]
looks great! can't wait to print a couple different options now :)
