### ISSUE TITLE
Manuform: parametric column curvavture

### ISSUE THREAD

**Issue by dereknheiley** [ibnuda/dactyl-keyboard#35]
this builds off of (/ would work well in combination with) issue #34 

![d-hands](https://user-images.githubusercontent.com/3382160/86537409-db43bc80-bebc-11ea-8117-595ddc823627.jpg)

i would like to have the (parametric?) option for tighter radius column curvature for pinky, and possibly index fingers, simply shifting things down with different column stagger is only half the solution since then the lower pinky and index fingers would then be harder to reach (for me), so in addition to #34 where the top of the column could be adjusted closer for some fingers, the overall curvature would need to be updated so the relative position of the lowest row for the pinky and index finger doesn't really move

**Comment by ibnuda** [comment]
please check the site.

**Comment by dereknheiley** [comment]
:mr-burns-excellent:
