### ISSUE TITLE
timestamp filenames when using generate button

### ISSUE THREAD

**Issue by dereknheiley** [ibnuda/dactyl-keyboard#38]
relying on the OS / Browser to increment manuform(#).scad isn't that great if you want to keep track of a couple of different models, particularly if you start to move one or two of them out of the downloads folder.

Renaming each after generating it can quickly get tedious, so something like `manuform-utc-yyyy-mm-dd-hh-mm-ss.scad` would help give unique filenames with the timestamp of when they were generated

**Comment by ibnuda** [comment]
should be fixed already.

**Comment by dereknheiley** [comment]
thanks!
