### ISSUE TITLE
Manuform: Dot missing before .scad in filename

### ISSUE THREAD

**Issue by jgandert** [ibnuda/dactyl-keyboard#42]
When exporting a Manuform scad file, there's no dot before `scad` so the filename ends up being something like:

`lightcycle2020.07.11-10.40.20scad`

I think this is where the problem happens: 

https://github.com/ibnuda/dactyl-keyboard/blob/d8f97003907d165f79a98c4104e95fe904977f87/src/dactyl_keyboard/handler.clj#L224

**Comment by ibnuda** [comment]
should be fixed already. please check the site.

**Comment by jgandert** [comment]
Thanks!
