### ISSUE TITLE
Lightcycle: an object is blocking one of the thumb keys

### ISSUE THREAD

**Issue by Razerban** [ibnuda/dactyl-keyboard#5]
Using the default configuration from the UI, I found that an object is blocking one of the thumb keys.
The following images describe the issue:
<img width="925" alt="Screenshot 2020-04-15 at 11 29 26" src="https://user-images.githubusercontent.com/7271421/79322410-17dec800-7f0d-11ea-953e-f990a928749a.png">
<img width="946" alt="Screenshot 2020-04-15 at 11 31 01" src="https://user-images.githubusercontent.com/7271421/79322420-1a412200-7f0d-11ea-823c-edcc112ee8a5.png">
<img width="853" alt="Screenshot 2020-04-15 at 11 31 22" src="https://user-images.githubusercontent.com/7271421/79322424-1ad9b880-7f0d-11ea-8971-647d0004fe9c.png">

I think that it's the corner of the last key in the grid.
When I choose **Thumb Position in X direction (left/right): Farther to body**, I can still see the corner but it's no longer blocking the key.
When I choose **Thumb Position in Z direction (up/down): Higher to body**, I can no longer see the corner.

**Comment by ibnuda** [comment]
ah right. I haven't checked every option exhaustively. for this problem, I think the better choice is to set the minimum thumb height. what do you think?

edit: actually, it's the `connectors`. especially on the last row and the second column. i will fix it.

**Comment by ibnuda** [comment]
uses lastrow:

![Schermafdruk_2020-04-15_21-11-34](https://user-images.githubusercontent.com/8169908/79347430-e4785980-7f5d-11ea-8748-4e42f63cf915.png)

doesn't use lastrow:
![Schermafdruk_2020-04-15_21-12-30](https://user-images.githubusercontent.com/8169908/79347454-e93d0d80-7f5d-11ea-8dfd-1a51c82a8edd.png)

i will push the fix in the next commit.

**Comment by Razerban** [comment]
> ah right. I haven't checked every option exhaustively. for this problem, I think the better choice is to set the minimum thumb height. what do you think?
> 
> edit: actually, it's the `connectors`. especially on the last row and the second column. i will fix it.

Sorry for the delay of my reply.
Yes, it's definetely the `connectors`. I saw that you have pushed a fix, I'll test it later and let you know ;)

**Comment by Razerban** [comment]
The problem seems to be fixed! Great!
