### ISSUE TITLE
Reduce thickness of case 

### ISSUE THREAD

**Issue by RaoulDuke-Esq** [ibnuda/dactyl-keyboard#59]
I would like to reduce the overall thickness (depth) of the shell of the Manuform variant because I find the case to be too thick to accommodate Kailh switches or to use Amoeba PCBs because the case is so thick that the pins on the switches can't reach the PCBs.  I found "plate-thickness" in common.clj which can be adjusted so Kailh switches actually clip in properly, but this does not solve the problem of the overall socket being too deep.

I believe that reducing the thickness would also help with #46 - the external holders do not fit because they are not made to accommodate the extra thick walls of this case.

Where can I adjust the thickness of the walls/case?

**Comment by happysalada** [comment]
If I understand you correctly, I have a similar problem.
Currently I am experimenting with the "web-thickness" parameter
https://github.com/ibnuda/dactyl-keyboard/blob/refaktor/src/dactyl_keyboard/common.clj#L367
That will reduce the thickness of the plate.
However, it won't help you with the socket thickness.

To reduce the thickness of the socket you have to play with the params over here
https://github.com/ibnuda/dactyl-keyboard/blob/refaktor/src/dactyl_keyboard/common.clj#L266
When I added choc switches, that's what I changed. You can adjust the bottom and the top of the socket wall to adjust the thickness.
I'm not sure if it makes perfect sense. If you try a couple of values, it will make sense I believe.

**Comment by happysalada** [comment]
I just issued a PR to fix this problem for the choc-switch.
https://github.com/ibnuda/dactyl-keyboard/pull/65
Once the PR is merged, can you check and let me know if that is the problem you're having with the kailh switches?

**Comment by aabbett** [comment]
Will do!

**Comment by c10l** [comment]
Has anyone been able to test it with Kailh? If so, which switch profile is the one that works, choc?

Alternatively, would someone be able to implement the solution in this PR? https://github.com/tshort/dactyl-keyboard/pull/36

Thanks! :)

**Comment by happysalada** [comment]
I don't use kailh unfortunately. But now I think I see what you mean. The problem I solved with the choc was a different one.

the change in the PR you mentioned is only 14 lines!
https://github.com/tshort/dactyl-keyboard/pull/36/files
I don't have kailh switches to test though, let's leave this open until somebody can test it properly.

**Comment by c10l** [comment]
I'm not the OP but I'll be receiving Kailhs some time in the next few days. Happy to test them out and post my results here if someone else doesn't beat me to it. :)

I'd love to open a PR with the changes I linked above or similar, but Clojure is Greek to me and right now I don't have the bandwidth to dig into this unfortunately.

**Comment by c10l** [comment]
I've finally received my keyswitches. I've printed one slot of the choc version of this.

It mostly works. I can get the switch into the slot and it's fairly snug but it definitely doesn't hook to the border like it should.

![IMG_3019](https://user-images.githubusercontent.com/399431/99463849-97fb5f00-292e-11eb-8b87-9d4c735f6661.jpeg)
![IMG_3018](https://user-images.githubusercontent.com/399431/99463853-9b8ee600-292e-11eb-8aa9-71c8630359a4.jpeg)
![IMG_3020](https://user-images.githubusercontent.com/399431/99463859-9df14000-292e-11eb-9e52-214597177159.jpeg)

**Comment by c10l** [comment]
I've also tried to fit an amoeba PCB there, and indeed like @RaoulDuke-Esq said in the OP, it won't fit due to the depth of the socket in relation to the frame.

It might still work but it won't be too tight a fit and could end up falling off.

![IMG_3021](https://user-images.githubusercontent.com/399431/99464099-38ea1a00-292f-11eb-80c8-ca06e5901f4b.jpeg)
![IMG_3022](https://user-images.githubusercontent.com/399431/99464103-3a1b4700-292f-11eb-967e-a5564d5aedbd.jpeg)
![IMG_3023](https://user-images.githubusercontent.com/399431/99464105-3ab3dd80-292f-11eb-9f9c-4c07e6c30797.jpeg)

**Comment by happysalada** [comment]
I've also seen that the amoeba PCB doesn't fit. The choc pcb swap is different, I'll be testing that in the next few days.
I'm receiving a new version of the design with the choc switch. I'll be posting where I am at the moment so that anybody interested in this can have a look at the code for the choc and do something similar for the kailh.

**Comment by happysalada** [comment]
![IMG_1949](https://user-images.githubusercontent.com/5317234/99931271-3f491d80-2d97-11eb-880c-4154520825e5.JPG)

Here is the state of things with the choc switches.
The fit is pretty good. I didn't measure, but it took me 5-10 prints to get it correct.
If anybody is interested in tackling this issue, just look at `use-choc` in the code base. You can probably introduce a case statement for the type of switch used. Clojure might look a little foreign, but you won't need to do anything too complicated. Just modifying number values, printing and trying the result. Of course, feel free to post your question if you have any.

**Comment by c10l** [comment]
@RaoulDuke-Esq My merge request https://github.com/ibnuda/dactyl-keyboard/pull/68 has been merged. It adds an option for Kailh switches which seems to work fine for me.

If you could try it out and let us know if it works that would be great!

**Comment by RaoulDuke-Esq** [comment]
I checked this out in OpenSCAD and it looks really good!  The slots created will allow the switches to clip in nicely.  Thanks for this!  We should probably close this one and file a separate one for the thickness of the rear wall as it's two separate issues and you've nicely solved the Kailh support.

I'm hesitant to do another print just yet.  There's some things I noticed from the last one that I haven't yet filed issues for (and probably should).  Did you notice any of these with your most recent print?  It looks like they're still there when I preview in OpenSCAD but I would love a sanity check before I drop a bunch of issues: 
- rear wall thickness too much for use of the pro micro holders linked at the bottom of the configuration webpage
- screw inserts off-center on inside wall
- plate does not confirm to geometry of thumb cluster on the outside/bottom wall
- insufficient clearance for keycaps in thumb cluster (caps will hit each other or the walls of the case)

**Comment by c10l** [comment]
> rear wall thickness too much for use of the pro micro holders linked at the bottom of the configuration webpage

I tried this and I think it's more about the clearance in the hole itself. What happened to me was that the holder pushed the back part of the case too much until it snapped and broke along the printer layer where the top of the hole is.

> plate does not confirm to geometry of thumb cluster on the outside/bottom wall

The generated plate seems to be all kinds of wrong. Once I'm happy with my case I'll create plates that conform to the bottom of the case by myself.

> insufficient clearance for keycaps in thumb cluster (caps will hit each other or the walls of the case)

I haven't noticed that. To be honest I'd rather the keys in the cluster were closer together as the way it is it's quite a reach for me.
