### ISSUE TITLE
Incorrect 4 columns handling

### ISSUE THREAD

**Issue by cub-uanic** [ibnuda/dactyl-keyboard#61]
I'm using http://dactyl.siskam.link/manuform
When the layout is 4x4, I'm expecting to get each column to be for each finger.
Instead, it looks like the columns are for (left-to-right, for right half): index, index, middle, ring and seems there is no column for the pinky.
Try to generate with the attached config and hope you'll see what I mean.

[no-pinky-column.json.txt](https://github.com/ibnuda/dactyl-keyboard/files/5412080/no-pinky-column.json.txt)

**Comment by ibnuda** [comment]
something like this? should've been fixed. please check the site. and then on "Inner Index Finger's Column?", choose "Without."
![Screenshot_20201108_002152](https://user-images.githubusercontent.com/8169908/98447621-d2a80f00-2158-11eb-89e0-f3af496949ce.png)
