### ISSUE TITLE
Feature: Option for wall thickness

### ISSUE THREAD

**Issue by fi0** [ibnuda/dactyl-keyboard#71]
Please add an option for wall thickness in dactyl. :)
related https://github.com/ibnuda/dactyl-keyboard/issues/26

**Comment by happysalada** [comment]
The option for wall thickness is coming in a future PR, but this one, adds the ability to configure web-thickness.
Which is the top part of the keyboard around the key holes.
Just thought you might be interested.
https://github.com/ibnuda/dactyl-keyboard/pull/82
