### ISSUE TITLE
Dactyl Lightcycle: Thumb count number 6 isn't working

### ISSUE THREAD

**Issue by Razerban** [ibnuda/dactyl-keyboard#8]
Choosing thumb count 6 yields the same model as choosing thumb count 5.
I think there is another case that is missing here https://github.com/ibnuda/dactyl-keyboard/blob/18c4e326e5ad68f385390669c84b1e0bd03ddbd6/src/dactyl_keyboard/handler.clj#L139-L142

**Comment by ibnuda** [comment]
ah, you're correct.
