### ISSUE TITLE
Inner Index Finger's Column not working

### ISSUE THREAD

**Issue by antoniotrkdz** [ibnuda/dactyl-keyboard#84]
Hi,
When using the online generator there is no difference between the model generated with and the one generated without this parameter.
It is a recent issue as it worked around the end of April (when I got a model with this parameter).

It would be great if this option could be restored, thanks.

**Comment by ibnuda** [comment]
try use the latest `manuform.json`.

**Comment by ibnuda** [comment]
https://github.com/ibnuda/dactyl-keyboard/commit/b6cb9ce4d5d690aba0392d344850ccd56a13f359 should fix it.

**Comment by antoniotrkdz** [comment]
Hi.
Yes, the issue is solved.
Thank you.
