### ISSUE TITLE
A project to demo dactyl manuform paramaters

### ISSUE THREAD

**Issue by yejianfengblue** [ibnuda/dactyl-keyboard#88]
Adding preview render as suggested in issue https://github.com/ibnuda/dactyl-keyboard/issues/36 is awesome. I created a [project](https://github.com/yejianfengblue/dactyl-generator-demo) to demo most parameters of dactyl manuform using the API. You can reference it somewhere in the dactyl generator web page. So people don't need to generate many model to test the param, which would tax the server.

**Comment by ibnuda** [comment]
i've put a link to your repo. thanks.
