### ISSUE TITLE
Manuform 2 of 6 thumb key holes are half stopped up

### ISSUE THREAD

**Issue by yejianfengblue** [ibnuda/dactyl-keyboard#93]
Manuform page default parameter values are used and 2 of 6 thumb key holes are half stopped up. I don't know whether it's related to the three mini code change. The last normal mode was generated at 2021-07-14 02:00 UTC+0

![manuform-case-right-thumb-6](https://user-images.githubusercontent.com/28599139/126964910-9ce77109-2c32-4db8-965a-e97620c9426b.png)

**Comment by ibnuda** [comment]
thanks, i did not realise it. fixed. ![Screenshot_20210726_180454](https://user-images.githubusercontent.com/8169908/126979127-909458b3-2dcd-4795-a88f-3414f9f256cd.png)
